# Use this open statement to create an OpenGL view:
/vis/open OGL

# Draw geometry:
/vis/drawVolume

# Specify view angle:
# from above
# /vis/viewer/set/viewpointThetaPhi 180 0 deg
# from the side
/vis/viewer/set/viewpointThetaPhi 270 0 deg
#
#/vis/viewer/set/viewpointThetaPhi 70 20

# Specify zoom value:
/vis/viewer/zoomTo 2.


# Specify style (surface or wireframe):
#/vis/viewer/set/style wireframe
#/vis/viewer/set/style surface
#/vis/viewer/set/background black


# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 0.05 m
/vis/scene/add/axes 0 0 0


# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
/vis/scene/add/hits
#
# To draw only gammas:
/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add pi-
/vis/filtering/trajectories/particleFilter-0/add e-
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/add opticalphoton
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set pi- brown
/vis/modeling/trajectories/drawByParticleID-0/set mu- blue
/vis/modeling/trajectories/drawByParticleID-0/set gamma yellow
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton cyan


# Draw hits at end of event:
/vis/scene/add/hits
/vis/scene/add/trajectories


#/units/list
#/gun/energy 0.5 GeV
/gun/particle e-
#/gun/pos/type Plane
#/gun/pos/shape Square
#/gun/pos/halfx 3.0 mm
#/gun/pos/halfy 3.0 mm

# 3 degrees tilt
#/gps/direction 0.0523 0.0523 0.9986


/run/beamOn 1
